version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    groups:
      futures:
        patterns:
          - "futures*"
      grpc:
        patterns:
          - "prost*"
          - "tonic*"
      hyper:
        patterns:
          - "hyper*"
      pin-project:
        patterns:
          - "pin-project*"
      rand:
        patterns:
          - "rand"
          - "rand_*"
      regex:
        patterns:
          - "regex"
          - "regex-*"
      tracing:
        patterns:
          - "tracing*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
