// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: opaque_route.proto

package opaque_route

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Used to indicate that the policy is invalid.
type Invalid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invalid) Reset() {
	*x = Invalid{}
	mi := &file_opaque_route_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invalid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invalid) ProtoMessage() {}

func (x *Invalid) ProtoReflect() protoreflect.Message {
	mi := &file_opaque_route_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invalid.ProtoReflect.Descriptor instead.
func (*Invalid) Descriptor() ([]byte, []int) {
	return file_opaque_route_proto_rawDescGZIP(), []int{0}
}

func (x *Invalid) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Used to indicate that traffic is forbidden.
type Forbidden struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Forbidden) Reset() {
	*x = Forbidden{}
	mi := &file_opaque_route_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Forbidden) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forbidden) ProtoMessage() {}

func (x *Forbidden) ProtoReflect() protoreflect.Message {
	mi := &file_opaque_route_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forbidden.ProtoReflect.Descriptor instead.
func (*Forbidden) Descriptor() ([]byte, []int) {
	return file_opaque_route_proto_rawDescGZIP(), []int{1}
}

var File_opaque_route_proto protoreflect.FileDescriptor

const file_opaque_route_proto_rawDesc = "" +
	"\n" +
	"\x12opaque_route.proto\x12\x1dio.linkerd.proxy.opaque_route\"#\n" +
	"\aInvalid\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\v\n" +
	"\tForbiddenB7Z5github.com/linkerd/linkerd2-proxy-api/go/opaque_routeb\x06proto3"

var (
	file_opaque_route_proto_rawDescOnce sync.Once
	file_opaque_route_proto_rawDescData []byte
)

func file_opaque_route_proto_rawDescGZIP() []byte {
	file_opaque_route_proto_rawDescOnce.Do(func() {
		file_opaque_route_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_opaque_route_proto_rawDesc), len(file_opaque_route_proto_rawDesc)))
	})
	return file_opaque_route_proto_rawDescData
}

var file_opaque_route_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_opaque_route_proto_goTypes = []any{
	(*Invalid)(nil),   // 0: io.linkerd.proxy.opaque_route.Invalid
	(*Forbidden)(nil), // 1: io.linkerd.proxy.opaque_route.Forbidden
}
var file_opaque_route_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_opaque_route_proto_init() }
func file_opaque_route_proto_init() {
	if File_opaque_route_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_opaque_route_proto_rawDesc), len(file_opaque_route_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_opaque_route_proto_goTypes,
		DependencyIndexes: file_opaque_route_proto_depIdxs,
		MessageInfos:      file_opaque_route_proto_msgTypes,
	}.Build()
	File_opaque_route_proto = out.File
	file_opaque_route_proto_goTypes = nil
	file_opaque_route_proto_depIdxs = nil
}
