// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.12.4
// source: opaque_route.proto

package opaque_route

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Used to indicate that the policy is invalid.
type Invalid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Invalid) Reset() {
	*x = Invalid{}
	mi := &file_opaque_route_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invalid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invalid) ProtoMessage() {}

func (x *Invalid) ProtoReflect() protoreflect.Message {
	mi := &file_opaque_route_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invalid.ProtoReflect.Descriptor instead.
func (*Invalid) Descriptor() ([]byte, []int) {
	return file_opaque_route_proto_rawDescGZIP(), []int{0}
}

func (x *Invalid) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Used to indicate that traffic is forbidden.
type Forbidden struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Forbidden) Reset() {
	*x = Forbidden{}
	mi := &file_opaque_route_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Forbidden) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forbidden) ProtoMessage() {}

func (x *Forbidden) ProtoReflect() protoreflect.Message {
	mi := &file_opaque_route_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forbidden.ProtoReflect.Descriptor instead.
func (*Forbidden) Descriptor() ([]byte, []int) {
	return file_opaque_route_proto_rawDescGZIP(), []int{1}
}

var File_opaque_route_proto protoreflect.FileDescriptor

var file_opaque_route_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6f, 0x70, 0x61, 0x71, 0x75, 0x65, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x69, 0x6f, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x6f, 0x70, 0x61, 0x71, 0x75, 0x65, 0x5f, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x22, 0x23, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x0b, 0x0a, 0x09, 0x46, 0x6f, 0x72, 0x62,
	0x69, 0x64, 0x64, 0x65, 0x6e, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x64, 0x2f, 0x6c, 0x69, 0x6e, 0x6b,
	0x65, 0x72, 0x64, 0x32, 0x2d, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x67,
	0x6f, 0x2f, 0x6f, 0x70, 0x61, 0x71, 0x75, 0x65, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_opaque_route_proto_rawDescOnce sync.Once
	file_opaque_route_proto_rawDescData = file_opaque_route_proto_rawDesc
)

func file_opaque_route_proto_rawDescGZIP() []byte {
	file_opaque_route_proto_rawDescOnce.Do(func() {
		file_opaque_route_proto_rawDescData = protoimpl.X.CompressGZIP(file_opaque_route_proto_rawDescData)
	})
	return file_opaque_route_proto_rawDescData
}

var file_opaque_route_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_opaque_route_proto_goTypes = []any{
	(*Invalid)(nil),   // 0: io.linkerd.proxy.opaque_route.Invalid
	(*Forbidden)(nil), // 1: io.linkerd.proxy.opaque_route.Forbidden
}
var file_opaque_route_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_opaque_route_proto_init() }
func file_opaque_route_proto_init() {
	if File_opaque_route_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_opaque_route_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_opaque_route_proto_goTypes,
		DependencyIndexes: file_opaque_route_proto_depIdxs,
		MessageInfos:      file_opaque_route_proto_msgTypes,
	}.Build()
	File_opaque_route_proto = out.File
	file_opaque_route_proto_rawDesc = nil
	file_opaque_route_proto_goTypes = nil
	file_opaque_route_proto_depIdxs = nil
}
