name: go

on:
  pull_request:
    paths:
      - go.*
      - '**/*.go'
      - '**/*.proto'
      - justfile
      - .github/workflows/go.yml

permissions:
  contents: read

jobs:
  go:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container: docker://ghcr.io/linkerd/dev:v50-go
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - run: just go-mod-check
      - run: just go-gen-check
      - run: just go-build
